In [2]:
from google.colab import files
uploaded = files.upload()

Saving olist_customers_dataset.csv to olist_customers_dataset (1).csv

In [3]:
from google.colab import files
uploaded = files.upload()

Saving olist_products_dataset.csv to olist_products_dataset.csv

In [4]:
from google.colab import files
uploaded = files.upload()

Saving olist_sellers_dataset.csv to olist_sellers_dataset.csv

In [5]:
from google.colab import files
uploaded = files.upload()

Saving olist_orders_dataset.csv to olist_orders_dataset.csv

In [6]:
from google.colab import files
uploaded = files.upload()

Saving olist_order_items_dataset.csv to olist_order_items_dataset.csv

In [7]:
from google.colab import files
uploaded = files.upload()

Saving olist_order_payments_dataset.csv to olist_order_payments_dataset.csv

In [8]:
from google.colab import files
uploaded = files.upload()

Saving olist_order_reviews_dataset.csv to olist_order_reviews_dataset.csv

In [14]:
import pandas as pd

orders = pd.read_csv("olist_orders_dataset.csv")
customers = pd.read_csv("olist_customers_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")
order_payments = pd.read_csv("olist_order_payments_dataset.csv")
order_reviews = pd.read_csv("olist_order_reviews_dataset.csv")

In [11]:
for file in os.listdir():
    print(file)

.config
olist_orders_dataset.csv
olist_order_items_dataset.csv
olist_products_dataset.csv
olist_order_payments_dataset.csv
olist_sellers_dataset.csv
olist_customers_dataset.csv
olist_customers_dataset (1).csv
olist_order_reviews_dataset.csv
sample_data

In [10]:
import os

print(os.listdir())

['.config', 'olist_orders_dataset.csv', 'olist_order_items_dataset.csv', 'olist_products_dataset.csv', 'olist_order_payments_dataset.csv', 'olist_sellers_dataset.csv', 'olist_customers_dataset.csv', 'olist_customers_dataset (1).csv', 'olist_order_reviews_dataset.csv', 'sample_data']

In [15]:
import sqlite3

conn = sqlite3.connect("olist.db")

In [16]:
orders.to_sql("orders", conn, if_exists="replace", index=False)
customers.to_sql("customers", conn, if_exists="replace", index=False)
order_items.to_sql("order_items", conn, if_exists="replace", index=False)
products.to_sql("products", conn, if_exists="replace", index=False)
sellers.to_sql("sellers", conn, if_exists="replace", index=False)
order_payments.to_sql("order_payments", conn, if_exists="replace", index=False)
order_reviews.to_sql("order_reviews", conn, if_exists="replace", index=False)

99224

In [17]:
query = "SELECT COUNT(*) FROM orders;"
pd.read_sql(query, conn)

   COUNT(*)
0     99441

In [18]:
query = """
SELECT order_status, COUNT(*)
FROM orders
GROUP BY order_status
"""

pd.read_sql(query, conn)

  order_status  COUNT(*)
0     approved         2
1     canceled       625
2      created         5
3    delivered     96478
4     invoiced       314
5   processing       301
6      shipped      1107
7  unavailable       609